export const actionTypes = {
  ADD_ORDER: "ADD_ORDER",
  DELETE_ORDERS: "DELETE_ORDERS",
  OPEN_ADD_PRODUCT: "OPEN_ADD_PRODUCT",
  SELECT_ORDER: "SELECT_ORDER",
  ADD_PRODUCT: "ADD_PRODUCT",
  EDIT_ORDER: "EDIT_ORDER",
  REMOVE_PRODUCT: "REMOVE_PRODUCT",
  EDIT_PRODUCT: "EDIT_PRODUCT",
  SELECT_PRODUCT_KEY_TO_EDIT: "SELECT_PRODUCT_KEY_TO_EDIT",
  SAVE_PRODUCT_KEY_EDIT: "SAVE_PRODUCT_KEY_EDIT",
};
